#!/bin/zsh

alias zshrc="vi $ZDOTDIR/.zshrc"
alias reload="source $ZDOTDIR/.zshrc"
alias history="fc -i -D -rl 1 | fzy -i -l 50"
alias h="history"
alias cl='clear'
alias mkdir='mkdir -pv'
alias ls='ls --color=auto -Fh'
alias l='ls -C'
alias la='ls -CA'
alias ll='ls -l'
alias lla='ls -lA'
alias lr='ls -R'
alias llr='ls -lR'
