#!/bin/zsh

alias py="python"
alias dj='py manage.py'
alias djm='py manage.py migrate'
alias djmm='py manage.py makemigrations'
alias djsm='py manage.py showmigrations'
alias djr='py manage.py runserver localhost:8080'
alias djdb='py manage.py dbshell'
alias djsh='py manage.py shell'
alias djt='TEST=1 py manage.py test'
